name: kiganjani_afya_check
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"
dependencies:
  web: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_snack_bar: 0.4.0
  intl: 0.19.0
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.2
  lottie: ^3.1.2
  icons_plus: ^5.0.0
  font_awesome_flutter: ^10.7.0
  google_nav_bar: ^5.0.6
  flutter_launcher_icons: ^0.13.1
  video_player: ^2.9.1
  chewie: ^1.7.5
  fl_chart: ^0.68.0
  babstrap_settings_screen: ^0.1.7
  provider: ^6.0.5
  http: ^1.2.2
  


flutter_icons:
  android: true
  ios: true
  image_path: assets/images/kiganjani_afya_check_logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - assets/appicon/kiganjani.png
    - assets/videos/obesity.mp4
    - assets/videos/BMI.mp4

#  fonts:
#    - family: Spectral
#      fonts:
#        - asset: assets/fonts/Spectral-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/Spectral-Medium.ttf
#          weight: 500
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Light.ttf
#          weight: 200
#        - asset: assets/fonts/Roboto-Bold.ttf
#          weight: 700

